backend:
  name: github
  repo: PrinMarjory/TeaLicious
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "teas"
    label: "Thés"
    folder: "src/content/teas"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"

    fields:
      - label: "Nom"
        name: "name"
        widget: "string"

      - label: "Marque"
        name: "brand"
        widget: "string"

      - label: "Type"
        name: "type"
        widget: "select"
        options:
          - label: "Thé noir"
            value: "black"
          - label: "Thé vert"
            value: "green"
          - label: "Thé blanc"
            value: "white"
          - label: "Oolong"
            value: "oolong"
          - label: "Pu-erh"
            value: "puerh"
          - label: "Rooibos"
            value: "rooibos"
          - label: "Infusion"
            value: "infusion"

      - label: "Origine"
        name: "origin"
        widget: "string"
        required: false

      - label: "Image"
        name: "image"
        widget: "image"
        required: false

      - label: "Ingrédients"
        name: "ingredients"
        widget: "list"
        required: false

      - label: "Description courte"
        name: "shortDescription"
        widget: "text"

      - label: "Description longue"
        name: "longDescription"
        widget: "markdown"
        required: false

      - label: "Température"
        name: "temperature"
        widget: "number"
        value_type: "int"
        required: false

      - label: "Temps d'infusion"
        name: "steepingTime"
        widget: "number"
        value_type: "int"
        required: false